"""agent field updated with email

Revision ID: 022ae3e36ca7
Revises: 81e0457a05c4
Create Date: 2025-10-12 08:10:56.012017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '022ae3e36ca7'
down_revision: Union[str, Sequence[str], None] = '81e0457a05c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('email', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'email')
    # ### end Alembic commands ###
