"""agent email made unique

Revision ID: 076d8ab467f3
Revises: 1a4033121fc5
Create Date: 2025-10-12 08:27:23.334867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '076d8ab467f3'
down_revision: Union[str, Sequence[str], None] = '1a4033121fc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'agents', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agents', type_='unique')
    # ### end Alembic commands ###
