"""agent field updated with password

Revision ID: 1a4033121fc5
Revises: 022ae3e36ca7
Create Date: 2025-10-12 08:19:46.217864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a4033121fc5'
down_revision: Union[str, Sequence[str], None] = '022ae3e36ca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'password')
    # ### end Alembic commands ###
