"""agent field updated with name and description

Revision ID: 81e0457a05c4
Revises: 6ae911f487c2
Create Date: 2025-10-12 08:05:41.016246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81e0457a05c4'
down_revision: Union[str, Sequence[str], None] = '6ae911f487c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('url', sa.String(), nullable=False))
    op.add_column('agents', sa.Column('name', sa.String(), nullable=False))
    op.add_column('agents', sa.Column('description', sa.String(), nullable=False))
    op.add_column('agents', sa.Column('contact', sa.String(), nullable=False))
    op.drop_column('agents', 'agentUrl')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('agentUrl', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('agents', 'contact')
    op.drop_column('agents', 'description')
    op.drop_column('agents', 'name')
    op.drop_column('agents', 'url')
    # ### end Alembic commands ###
