"""audio url field added to message model

Revision ID: bde584be52fe
Revises: 076d8ab467f3
Create Date: 2025-10-12 08:36:28.395641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bde584be52fe'
down_revision: Union[str, Sequence[str], None] = '076d8ab467f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('audioUrl', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'audioUrl')
    # ### end Alembic commands ###
