"""video argument correct

Revision ID: ca439cf91000
Revises: 87491f491e1a
Create Date: 2025-10-12 10:05:08.925667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca439cf91000'
down_revision: Union[str, Sequence[str], None] = '87491f491e1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('videoUrl', sa.String(), nullable=True))
    op.drop_column('messages', 'vidoeUrl')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('vidoeUrl', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'videoUrl')
    # ### end Alembic commands ###
